import { StyleSheet } from 'react-native';
import {
  Colors,
  horizontalScale,
  moderateScale,
  verticleScale,
} from '../../themes';

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#80808080',
  },
  modalContentContainer:{
     backgroundColor:Colors.light,
     width: '80%',
     height: '45%',
     alignSelf:'center',
     borderRadius: moderateScale(10)
  },
  container: {
    flex: 1,
    backgroundColor: Colors.light,
    position: 'relative',
  },
  avatar: {
    height: verticleScale(140),
    width: horizontalScale(60),
  },
  profileView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: horizontalScale(4),
    borderRadius: 2,
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: Colors.gray,
    marginTop: verticleScale(5),
    paddingHorizontal: horizontalScale(14),
    paddingVertical: verticleScale(18),
  },
  name: {
    fontWeight: 'bold',
    fontSize: moderateScale(22),
    color: Colors.orange,
  },
  text: {
    color: Colors.dark,
    fontWeight: '400',
    fontSize: moderateScale(15),
  },
  scrollContainer: {
    backgroundColor: Colors.light,
    position: 'absolute',
    height: '100%',
    width: '96%',
    alignSelf: 'center',
    top: 10,
    borderRadius: moderateScale(10),
    elevation: 20,
    shadowColor: Colors.gray,
  },
  banner: {
    width: '100%',
    height: verticleScale(135),
    borderRadius: moderateScale(10),
  },
  imageView: {
    marginTop: verticleScale(4),
    marginHorizontal: horizontalScale(2),
    marginBottom: verticleScale(20),
  },
  orangeContainer: {
    height: '15%',
    backgroundColor: Colors.orange,
    borderBottomEndRadius: 10,
    borderBottomLeftRadius: 10,
  },
  availabilityStatusText: {
    color: Colors.dark,
    fontWeight: '500',
    fontSize: moderateScale(18),
  },
  button: {
    borderWidth: 2,
    height: verticleScale(60),
    width: horizontalScale(60),
    borderRadius: moderateScale(20),
    justifyContent: 'center',
    borderColor: Colors.orange,
  },
  buttonFillOrange: {
    borderWidth: 2,
    height: verticleScale(60),
    width: horizontalScale(60),
    borderRadius: moderateScale(20),
    justifyContent: 'center',
    borderColor: Colors.orange,
    backgroundColor: Colors.orange,
  },
  circle: {
    height: '88%',
    borderWidth: 2,
    width: '39%',
    borderRadius: 2000,
    marginLeft: verticleScale(5),
    borderColor: Colors.orange,
  },
  circleFill: {
    height: '88%',
    width: '39%',
    borderRadius: 2000,
    marginHorizontal: verticleScale(5),
    position: 'absolute',
    right: 0,
    backgroundColor: Colors.light,
  },
  statusContainer: {
    marginTop: verticleScale(25),
    marginHorizontal: horizontalScale(4),
    borderWidth: 1,
    borderColor: Colors.offShade,
    borderRadius: moderateScale(5),
    paddingBottom: verticleScale(20),
  },
  statusContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(14),
    marginTop: verticleScale(35),
  },
  wishToGetText: {
    color: Colors.dark,
    paddingHorizontal: horizontalScale(14),
    justifyContent: 'center',
    fontSize: moderateScale(16),
    marginBottom: verticleScale(15),
    fontWeight: '400',
  },
  bottomSpace: {
    marginBottom: verticleScale(20),
  },
  birthDetailsButton: {
    backgroundColor: Colors.cornFlowerBlue,
    marginHorizontal: horizontalScale(14),
    borderRadius: moderateScale(10),
    marginTop: verticleScale(20),
  },
  birthDetailsText: {
    padding: moderateScale(10),
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: moderateScale(18),
    color: Colors.light,
  },
  getDetailsContainer: {
    paddingVertical: verticleScale(25),
  },
  freeVoiceChatContainer: {
    flexDirection: 'row',
    marginTop: verticleScale(25),
    marginHorizontal: horizontalScale(4),
    borderWidth: 1,
    borderColor: Colors.offShade,
    borderRadius: moderateScale(5),
    paddingHorizontal: horizontalScale(14),
    paddingVertical: verticleScale(30),
    justifyContent: 'space-between',
  },
  boostProfileButton: {
    backgroundColor: Colors.cornFlowerBlue,
    borderRadius: moderateScale(10),
    marginTop: verticleScale(25),
    marginHorizontal: horizontalScale(4),
  },
});

export default styles;
