export const ScreenString = {
  divineHelp: 'Dive Divine',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  newUser: 'New User?',
  register: 'Register',
  requestForEnrollingVarta: 'Request For Enrolling Varta',
  selectGender: 'Select Gender',
  male: 'Male',
  female: 'Female',
  errorGender: 'Please select a gender.',
  deviceKnown: 'System Known',
  set: 'Set',
  cancel: 'Cancel',
  language: 'Select Language(s)',
  termsAndCondtion: ' Terms And Conditions.',
  sendRequest: 'Send Request',
  alreadyHaveAccount: 'Already have an Account?',
  check: 'By checking, I Agree to',
  lekhaJhoka: 'Lekha Jhoka',
  divineWelcome: 'Divine Welcome,',
  wishToGetBirthDetails:
    'Wish to get birth detail and birth chat during ongoing call, click below.',
  getBirthDetails: 'Get Birth Details',
  boostProfile: 'Boost My Profile',
  updateProfile: 'Update Profile',
  category: 'Category',
  selectedCategories: 'Selected Categories',
  update: 'Update',
  dailyCredit: 'Daily Credits',
  callDetais: 'Call Details',
  details: ' Search Details',
  goLive: 'Press To Go Live',
  earningDetails: 'Earning Details',
  privateCallRate: 'Rate for Call or PrivateCall and Chat',
  liveAudio: 'Rate for Live Audio Call',
  liveVideo: 'Rate for Live Video Call',
  rateText: 'Rate(Rs/min)',
  discount: 'Discount ( % )',
  discountedRate: 'Discounted Rate(Rs/min)',
};

export const ValidationStrings = {
  required: 'It is a required field.',
  min: 'Minimum 8 character required.',
  invalidMail: 'Invalid Email.',
  min3: 'Minimum 3 characters required',
  noMatch: 'Password does not match.',
  aadhaarInvalid: 'Aadhar number is not valid',
  phoneInvalid: 'Phone Number is not valid',
  negativeExperience: "Experience can't be negative.",
  invalidExperience: 'Please enter a valid experience.',
  amountGreaterThanZero: 'Amount should be greater than 0.',
  invalidAmount: 'Please enter a valid amount.',
  negativeRate: "Amount can't be negative.",
  range: 'Enter between 0 to 100.',
};
