export const ScreenString = {
  divineHelp: 'Dive Divine',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  newUser: 'New User?',
  register: 'Register',
  requestForEnrollingVarta: 'Request For Enrolling Varta',
  selectGender: 'Select Gender',
  male: 'Male',
  female: 'Female',
  errorGender: 'Please select a gender.',
  deviceKnown: 'System Known',
  set: 'Set',
  cancel: 'Cancel',
  language: 'Select Language(s)',
  termsAndCondtion: ' Terms And Conditions.',
  sendRequest: 'Send Request',
  alreadyHaveAccount: 'Already have an Account?',
  check: 'By checking, I Agree to',
  lekhaJhoka: 'Lekha Jhoka',
  divineWelcome: 'Divine Welcome,',
  wishToGetBirthDetails:
    'Wish to get birth detail and birth chat during ongoing call, click below.',
  getBirthDetails: 'Get Birth Details',
  boostProfile: 'Boost My Profile',
  updateProfile: 'Update Profile',
  category: 'Category',
  selectedCategories: 'Selected Categories',
  update: 'Update',
  dailyCredit: 'Daily Credits',
  callDetais: 'Call Details',
  details: ' Search Details',
  goLive: 'Press To Go Live',
  earningDetails: 'Earning Details',
  privateCallRate: 'Rate for Call or PrivateCall and Chat',
  liveAudio: 'Rate for Live Audio Call',
  liveVideo: 'Rate for Live Video Call',
  rateText: 'Rate(Rs/min)',
  discount: 'Discount ( % )',
  discountedRate: 'Discounted Rate(Rs/min)',
  iWillbeOnleave: 'I will be on leave for',
  days: 'day(s)',
  selectValidDate: 'Select Valid Dates.',
  applyForLeave: 'Apply For Leave',
  enterReason: 'Please Enter a Valid Reason.',
  systemKnownError: 'Please select a System.',
  languageError: 'Please select language(s).',
  selectLanguages: 'Select Languages',
  acceptTerms: 'Please, check terms and conditions.',
  important: 'Important',
  respectPolicy:
    '* Respect Lekha Jhoka terms and condition as on violation necessary actions can be taken and one may be banned from using the app.',
  proceed: 'Proceed',
  unavailable: 'Unavailable For',
  videoCall: 'Video Call',
  chat: 'Chat',
  call: 'Call',
  unlimited: 'Unlimited free call and chats',
  myFollowers: 'My Followers',
  callPickupRate: 'Call Pickup Rate',
  chatPickupRate: 'Chat Pickup Rate',
  freeCallChatConversionRate: 'Free Call/Chat Conversion Rate',
  chatResponseRanking: 'Chat Response Ranking',
  chatReponseTime: 'Chat Response Time',
  reviews: 'Reviews',
  rating: 'Ratings',
  howAboveFactors: 'How Above Factors Calculated :',
  freeCallConversion: 'Free Call/Chat Conversion :',
  freeCallConversionCalculation:
    "The tally of free calls/chats I've received, and how many of those users have become repeat customers.",
  chatRateCalculation: 'Successful chat taken by me in a month.',
  callRateCalculation: 'Successful call taken by me in a month.',
  chatResponseRankingCalculation: 'My ranking as per my response time.',
  chatReponseTimeCalculation: 'Average time taken by me to handle a question.',
  from: 'From',
  to: 'To',
  report: 'Find Report',
  selectMonth: 'Select Month',
  selectYear: 'Select Year',
  signOut: 'Sign Out',
  support: 'Support',
  shareProfile: 'Share Profile',
  raiseTicket: 'Raise Ticket',
  mentionSubject: 'Please mention the subject.',
  mentionConcern: 'Please mention your concern.',
};

export const ValidationStrings = {
  required: 'It is a required field.',
  min: 'Minimum 8 character required.',
  invalidMail: 'Invalid Email.',
  min3: 'Minimum 3 characters required',
  noMatch: 'Password does not match.',
  aadhaarInvalid: 'Aadhar number is not valid',
  phoneInvalid: 'Phone Number is not valid',
  negativeExperience: "Experience can't be negative.",
  invalidExperience: 'Please enter a valid experience.',
  amountGreaterThanZero: 'Amount should be greater than 0.',
  invalidAmount: 'Please enter a valid amount.',
  negativeRate: "Amount can't be negative.",
  range: 'Enter between 0 to 100.',
};

export const PlaceholderStrings = {
  reasonForLeave: 'Specify the reason for leave(s)....',
  subject: 'Subject',
  yourConcern: 'Your Concern',
};
